package JobPortal;

/**
 *
 * @author 804653
 * @version 0.0.1
 */
import java.util.ArrayList;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;

public class SearchGUI extends javax.swing.JFrame {

    private String host = "jdbc:derby://localhost:1527/Job_Portal";
    private String uName = "Job_Portal";
    private String uPass = "Job_Portal";
    private String searchSql = "Select * from JOBS where";
    private String filterBySectorConsumerServices;
    private String filterBySectorFinance;
    private String filterBySectorConstruction;
    private String filterBySectorBasicIndustries;
    private String filterBySectorPublicUtilities;
    private String filterBySectorTransportation;
    private String filterByJobTypeFullTime;
    private String filterByJobTypePartTime;
    private String filterByJobTypePermanent;
    private String filterByJobTypeTemporary;
    private String filterByJobTypeInternship;
    private String filterByCountrySpain;
    private String filterByCountryGermany;
    private String filterByCountryFrance;
    private String filterByCountryNorway;
    private String filterByCountryGreece;
    private String keyword = "''";

    private Connection con;
    private ResultSet rs;
    private Statement stmt;

    /**
     * Creates new form NewJFrame
     */
    public SearchGUI() {
        initComponents();

        try {

            con = DriverManager.getConnection(host, uName, uPass);

        } catch (SQLException err) {
            System.out.println(err.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        menuBar3 = new java.awt.MenuBar();
        menu5 = new java.awt.Menu();
        menu6 = new java.awt.Menu();
        searchFrame = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        signInButton = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        searchFilters = new javax.swing.JPanel();
        jobTypeLable = new javax.swing.JLabel();
        partTimeCheckBox = new javax.swing.JCheckBox();
        permanentCheckBox = new javax.swing.JCheckBox();
        temporaryCheckBox = new javax.swing.JCheckBox();
        internshipCheckBox = new javax.swing.JCheckBox();
        jobSectorLable = new javax.swing.JLabel();
        fullTimeCheckBox = new javax.swing.JCheckBox();
        consumerServiceCheckBox = new javax.swing.JCheckBox();
        financeCheckBox = new javax.swing.JCheckBox();
        constructionCheckBox = new javax.swing.JCheckBox();
        transportationCheckBox = new javax.swing.JCheckBox();
        publicUtilitiesCheckBox = new javax.swing.JCheckBox();
        basicIndustriesCheckBox = new javax.swing.JCheckBox();
        countryLable = new javax.swing.JLabel();
        spainCheckBox = new javax.swing.JCheckBox();
        germanyCheckBox = new javax.swing.JCheckBox();
        franceCheckBox = new javax.swing.JCheckBox();
        norwayCheckBox = new javax.swing.JCheckBox();
        greeceCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane(resultsPanel);
        resultsPanel = new javax.swing.JPanel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        menu5.setLabel("File");
        menuBar3.add(menu5);

        menu6.setLabel("Edit");
        menuBar3.add(menu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchFrame.setVisible(true);

        signInButton.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        signInButton.setText("Sign in");
        signInButton.setAlignmentY(0.0F);

        searchTextField.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        searchTextField.setText("Search");
        searchTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusLost(evt);
            }
        });
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        searchButton.setText("Find Jobs ");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(signInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signInButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchTextField)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jobTypeLable.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jobTypeLable.setText("Job Type ");

        partTimeCheckBox.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        partTimeCheckBox.setText("Part-time");

        permanentCheckBox.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        permanentCheckBox.setText("Permanent ");

        temporaryCheckBox.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        temporaryCheckBox.setText("Temporary");

        internshipCheckBox.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        internshipCheckBox.setText("Intership");

        jobSectorLable.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jobSectorLable.setText("Job Sector");

        fullTimeCheckBox.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        fullTimeCheckBox.setText("Full-time ");
        fullTimeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullTimeCheckBoxActionPerformed(evt);
            }
        });

        consumerServiceCheckBox.setText("Consumer Services");
        consumerServiceCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                consumerServiceCheckBoxStateChanged(evt);
            }
        });
        consumerServiceCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumerServiceCheckBoxActionPerformed(evt);
            }
        });

        financeCheckBox.setText("Finance");
        financeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financeCheckBoxActionPerformed(evt);
            }
        });

        constructionCheckBox.setText("Construction ");
        constructionCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                constructionCheckBoxActionPerformed(evt);
            }
        });

        transportationCheckBox.setText("Transportation");
        transportationCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportationCheckBoxActionPerformed(evt);
            }
        });

        publicUtilitiesCheckBox.setText("Public Utilities");

        basicIndustriesCheckBox.setText("Basic Industries");
        basicIndustriesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicIndustriesCheckBoxActionPerformed(evt);
            }
        });

        countryLable.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        countryLable.setText("Country");

        spainCheckBox.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        spainCheckBox.setText("Spain");

        germanyCheckBox.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        germanyCheckBox.setText("Germany");
        germanyCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                germanyCheckBoxActionPerformed(evt);
            }
        });

        franceCheckBox.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        franceCheckBox.setText("France");

        norwayCheckBox.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        norwayCheckBox.setText("Norway");

        greeceCheckBox.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        greeceCheckBox.setText("Greece");

        javax.swing.GroupLayout searchFiltersLayout = new javax.swing.GroupLayout(searchFilters);
        searchFilters.setLayout(searchFiltersLayout);
        searchFiltersLayout.setHorizontalGroup(
            searchFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fullTimeCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jobSectorLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(financeCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(searchFiltersLayout.createSequentialGroup()
                .addGroup(searchFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consumerServiceCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(constructionCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(basicIndustriesCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(publicUtilitiesCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transportationCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(searchFiltersLayout.createSequentialGroup()
                .addGroup(searchFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jobTypeLable, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partTimeCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(permanentCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(temporaryCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(internshipCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(countryLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spainCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(germanyCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(franceCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(norwayCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(greeceCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        searchFiltersLayout.setVerticalGroup(
            searchFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchFiltersLayout.createSequentialGroup()
                .addComponent(jobSectorLable, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consumerServiceCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(financeCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(constructionCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transportationCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basicIndustriesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(publicUtilitiesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jobTypeLable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fullTimeCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(partTimeCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(permanentCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(temporaryCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(internshipCheckBox)
                .addGap(18, 18, 18)
                .addComponent(countryLable, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spainCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(germanyCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(franceCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(norwayCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(greeceCheckBox)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        resultsPanel.setLayout(new javax.swing.BoxLayout(resultsPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(resultsPanel);

        javax.swing.GroupLayout searchFrameLayout = new javax.swing.GroupLayout(searchFrame.getContentPane());
        searchFrame.getContentPane().setLayout(searchFrameLayout);
        searchFrameLayout.setHorizontalGroup(
            searchFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(searchFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchFilters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(searchFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(searchFrameLayout.createSequentialGroup()
                    .addGap(164, 164, 164)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        searchFrameLayout.setVerticalGroup(
            searchFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchFrameLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchFilters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(searchFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchFrameLayout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchFrame)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(searchFrame)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void germanyCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_germanyCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_germanyCheckBoxActionPerformed

    private void basicIndustriesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicIndustriesCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basicIndustriesCheckBoxActionPerformed

    private void transportationCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportationCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transportationCheckBoxActionPerformed

    private void constructionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_constructionCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_constructionCheckBoxActionPerformed

    private void financeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financeCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_financeCheckBoxActionPerformed

    private void consumerServiceCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumerServiceCheckBoxActionPerformed

    }//GEN-LAST:event_consumerServiceCheckBoxActionPerformed

    private void consumerServiceCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_consumerServiceCheckBoxStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_consumerServiceCheckBoxStateChanged

    private void fullTimeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullTimeCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullTimeCheckBoxActionPerformed

    /**
     * Creates the SQL query from the suer inputs of the search screen and
     * clears the displayed results.
     */
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        searchSql += "( Job_Title = '" + keyword + "'"
                + " or Job_Type = '" + keyword + "'"
                + " or Country = '" + keyword + "'"
                + " or Job_Description = '" + keyword + "'"
                + " or Sector = '" + keyword + "'"
                + " or Company_Name = '" + keyword + "'"
                + " or Salary = '" + keyword + "')";

        sectorFilter();
        jobTypeFilter();
        countryFilter();
        resultsPanel.removeAll();
        resultsPanel.updateUI();
        search();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed

    }//GEN-LAST:event_searchTextFieldActionPerformed
    /**
     * Sets the keyword for the search to the user input once the focus is lost.
     *
     * @param evt
     */
    private void searchTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusLost
        keyword = searchTextField.getText();
    }//GEN-LAST:event_searchTextFieldFocusLost

    private void searchTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusGained

    }//GEN-LAST:event_searchTextFieldFocusGained
/**
 * 
 * Adds to the SQL search string based on the check boxes selected for sector.
 * 
 */
    private void sectorFilter() {

        if (consumerServiceCheckBox.isSelected()
                || publicUtilitiesCheckBox.isSelected()
                || financeCheckBox.isSelected()
                || constructionCheckBox.isSelected()
                || transportationCheckBox.isSelected()
                || basicIndustriesCheckBox.isSelected()
                || publicUtilitiesCheckBox.isSelected()) {
            ArrayList<String> sectors = new ArrayList<String>();
            searchSql += "and( sector = ";

            if (consumerServiceCheckBox.isSelected()) {
                sectors.add("'Consumer Services'");
            };
            if (financeCheckBox.isSelected()) {
                sectors.add("'Finance'");
            };
            if (constructionCheckBox.isSelected()) {
                sectors.add("'construction'");
            };
            if (transportationCheckBox.isSelected()) {
                sectors.add("'transportation'");
            };
            if (basicIndustriesCheckBox.isSelected()) {
                sectors.add("'BasicIndustries'");
            };
            if (publicUtilitiesCheckBox.isSelected()) {
                sectors.add("'publicUtilities'");
            };
            for (int i = 0; i < sectors.size(); i++) {
                if (i < sectors.size() - 1) {
                    searchSql += sectors.get(i) + " or sector = ";
                } else {
                    searchSql += sectors.get(i) + ")";
                };
            };
        };
    }
/**
 * 
 * Adds to the SQL search string based on the check boxes selected for job type.
 * 
 */
    private void jobTypeFilter() {

        if (fullTimeCheckBox.isSelected()
                || partTimeCheckBox.isSelected()
                || permanentCheckBox.isSelected()
                || permanentCheckBox.isSelected()
                || temporaryCheckBox.isSelected()
                || internshipCheckBox.isSelected()) {
            ArrayList<String> jobType = new ArrayList<String>();

            searchSql += "and( Job_Type = ";

            if (fullTimeCheckBox.isSelected()) {
                jobType.add("'FULL_TIME'");
            };
            if (partTimeCheckBox.isSelected()) {
                jobType.add("'PART_TIME'");
            };
            if (permanentCheckBox.isSelected()) {
                jobType.add("'PERMANENT'");
            };
            if (temporaryCheckBox.isSelected()) {
                jobType.add("'TEMPORARY'");
            };
            if (internshipCheckBox.isSelected()) {
                jobType.add("'INTERNSHIP'");
            };
            for (int i = 0; i < jobType.size(); i++) {
                if (i < jobType.size() - 1) {
                    searchSql += jobType.get(i) + " or job_Type = ";
                } else {
                    searchSql += jobType.get(i) + ")";
                };
            };
        };
    }
/**
 * 
 * Adds to the SQL search string based on the check boxes selected for country.
 * 
 */
    private void countryFilter() {
        if (spainCheckBox.isSelected()
                || germanyCheckBox.isSelected()
                || franceCheckBox.isSelected()
                || norwayCheckBox.isSelected()
                || greeceCheckBox.isSelected()) {

            ArrayList<String> country = new ArrayList<String>();
            searchSql += "and( country = ";
            if (spainCheckBox.isSelected()) {
                country.add("'Spain'");
            };
            if (germanyCheckBox.isSelected()) {
                country.add("'Germany'");
            };
            if (franceCheckBox.isSelected()) {
                country.add("'France'");
            };
            if (norwayCheckBox.isSelected()) {
                country.add("'Norway'");
            };
            if (greeceCheckBox.isSelected()) {
                country.add("'Greece'");
            };
            for (int i = 0; i < country.size(); i++) {
                if (i < country.size() - 1) {
                    searchSql += country.get(i) + " or country = ";
                } else {
                    searchSql += country.get(i) + ")";
                };
            };
        };
    }
/**
 * 
 * Runs the search SQL based on the string created from the user inputs 
 * then displays the results on the GUI.
 * 
 */
    public void search() {
        try {
            stmt = con.createStatement();
            rs = stmt.executeQuery(searchSql);

            if (rs.next()) {
                while (rs.next()) {
                    SearchResult result = new SearchResult();

                    int Job_ID = rs.getInt("Job_ID");
                    String Job_Title = rs.getString("Job_Title");
                    String Job_Type = rs.getString("Job_Type");
                    java.util.Date Date = rs.getDate("APPLY_BY_DATE");
                    String Address = rs.getString("Address");
                    String Country = rs.getString("Country");
                    String Job_Description = rs.getString("Job_Description");
                    String Sector = rs.getString("Sector");
                    String Company_Name = rs.getString("Company_Name");
                    String Salary = rs.getString("Salary");

                    result.jobTitleLable.setText(Job_Title);
                    result.resultsJobTitleLable.setText(Company_Name);
                    result.resultsJobTypeLable.setText(Job_Type);
                    result.resultsApplyByDateLable.setText(Date.toString());
                    result.resultsSalaryLable.setText(Salary);
                    result.resultsCountryLable.setText(Country);
                    result.resultsSectorLable.setText(Sector);
                    result.resultsJobDescriptionLable.setText(Job_Description);

                    resultsPanel.add(result);
                    resultsPanel.revalidate();
                    resultsPanel.repaint();
                    
                    

                }
            } else {
                searchTextField.setText("no results found");
            }
            
            

        } catch (SQLException err) {
            System.out.println(err.getMessage());
        } finally {
            try {
                stmt.close();
            } catch (SQLException ex) {
                System.out.println("Could not close query");
            }

        }
        searchSql = "Select * from JOBS where";

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox basicIndustriesCheckBox;
    private javax.swing.JCheckBox constructionCheckBox;
    private javax.swing.JCheckBox consumerServiceCheckBox;
    private javax.swing.JLabel countryLable;
    private javax.swing.JCheckBox financeCheckBox;
    private javax.swing.JCheckBox franceCheckBox;
    private javax.swing.JCheckBox fullTimeCheckBox;
    private javax.swing.JCheckBox germanyCheckBox;
    private javax.swing.JCheckBox greeceCheckBox;
    private javax.swing.JCheckBox internshipCheckBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jobSectorLable;
    private javax.swing.JLabel jobTypeLable;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.Menu menu6;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.MenuBar menuBar3;
    private javax.swing.JCheckBox norwayCheckBox;
    private javax.swing.JCheckBox partTimeCheckBox;
    private javax.swing.JCheckBox permanentCheckBox;
    private javax.swing.JCheckBox publicUtilitiesCheckBox;
    private javax.swing.JPanel resultsPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchFilters;
    private javax.swing.JInternalFrame searchFrame;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel signInButton;
    private javax.swing.JCheckBox spainCheckBox;
    private javax.swing.JCheckBox temporaryCheckBox;
    private javax.swing.JCheckBox transportationCheckBox;
    // End of variables declaration//GEN-END:variables
}
